(define (problem dockerproblem)
   (:domain dockerdomain)
   (:objects c1 - container c2 - container tr - truck p1 - loc p2 - loc)
   (:init (truck-empty tr)
          (at p1 tr)
          (at p1 c1)
          (at p1 c2)
          (stacked c1 c2)
          (cTop c1)
          (cBot c2)
          (locationEmpty p2)
          (same c1 c1)          
          (same c2 c2)          
   )
   (:goal (and (at p2 c1)
             (at p2 c2)
             (at p2 tr)
             (cTop c2)
             (cBot c1)
             (stacked c2 c1)
             )))