(define (domain wumpus)
  (:requirements :strips :typing :fluents :conditional-effects)
  (:types
    coord player - object
    xCoord yCoord - coord
  )
  (:predicates
    (at ?player - player ?x - xCoord ?y - yCoord)
    (adjacent ?x1 - xCoord ?y1 - yCoord ?x2 - xCoord ?y2 - yCoord)
    (wumpus-at ?x - xCoord ?y - yCoord)
    (gold-at ?x - xCoord ?y - yCoord)
    (pit-at ?x - xCoord ?y - yCoord)
    (has-gold ?player - player)
    (wumpus-dead)
    (perceived-stench ?x - xCoord ?y - yCoord)
    (perceived-breeze ?x - xCoord ?y - yCoord)
    (perceived-glitter ?x - xCoord ?y - yCoord)
    (safe ?x - xCoord ?y - yCoord)
    (potential-wumpus ?x - xCoord ?y - yCoord)
    (potential-pit ?x - xCoord ?y - yCoord)
    (can-move ?player - player)
    (can-shoot ?player - player)
    (discovered ?x - xCoord ?y - yCoord)
  )
  (:functions
    (count)
    (n_adjacent)
  )

  (:action move
    :parameters (?player - player ?x1 - xCoord ?y1 - yCoord ?x2 - xCoord ?y2 - yCoord)
    :precondition (and (at ?player ?x1 ?y1) (adjacent ?x1 ?y1 ?x2 ?y2) (safe ?x2 ?y2) (can-move ?player))
    :effect (and (discovered ?x2 ?y2) (at ?player ?x2 ?y2) (not (at ?player ?x1 ?y1)) (not (can-move ?player)))
  )

  (:action update-neighbors
    :parameters (?player - player ?x - xCoord ?y - yCoord)
    :precondition (at ?player ?x ?y)
    :effect (and
      (forall (?nx - xCoord ?ny - yCoord)
        (when (adjacent ?x ?y ?nx ?ny)
          (and
            (when (not (perceived-breeze ?x ?y))
              (not (potential-pit ?nx ?ny)))
            (when (not (perceived-stench ?x ?y))
              (not (potential-wumpus ?nx ?ny)))
            (when (and (not (potential-wumpus ?x ?y)) (not (potential-pit ?x ?y)))
              (safe ?nx ?ny))
          )
        )
      )
      ;; Infer Wumpus location
      (forall (?sx - xCoord ?sy - yCoord)
        (when (and (perceived-stench ?sx ?sy) (discovered ?sx ?sy))
          (and
            (assign (count) 0)
            (assign (n_adjacent) 0)
            (forall (?nx - xCoord ?ny - yCoord)
              (when (adjacent ?sx ?sy ?nx ?ny)
                (and
                  (increase (n_adjacent) 1)
                  (when (and (not (perceived-stench ?nx ?ny)) (discovered ?nx ?ny))
                    (increase (count) 1)
                  )
                )
              )
            )
            (when (= (count) (- (n_adjacent) 1))
              (and
                (can-shoot ?player)
                (forall (?wx - xCoord ?wy - yCoord)
                  (when (and (adjacent ?sx ?sy ?wx ?wy) (potential-wumpus ?wx ?wy))
                    (wumpus-at ?wx ?wy)
                  )
                )
              )
            )
          )
        )
      )
      (can-move ?player)
    )
  )
)