(define (problem dockerproblem)
   (:domain dockerdomain)
   (:objects x1 - X x2 - X x3 - X x4 - X y1 - Y y2 - Y y3 - Y y4 - Y )
   (:init (wumpus x1 y3)
          (stench x1 y2)
          (stench x2 y3)
          (stench x1 y4)
          (breeze x2 y1)
          (breeze x4 y1)
          (breeze x2 y3)
          (breeze x3 y4)
          (breeze x4 y3)
          (breeze x3 y2)
          (wumpus x1 y2)
          (wumpus x1 y2)
                   
   )
   (:goal )
   )